sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vikram0207/hwrfrontend -f Dockerfile.dev .

script:
  - docker run -e CI=true vikram0207/hwrfrontend npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'dockerapp'
  env: 'dockerapp-env'
  bucket_name: 'elasticbeanstalk-us-east-2-585577319282'
  bucket_path: 'dockerapp'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
